#!/bin/bash

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
LIGHTGREEN='\033[1;32m'
NC='\033[0m' # No Color

ENDL="${NC}\n"

case "$1" in
	"init")
		printf "${GREEN}Initializing ${BLUE}@lahsone${YELLOW}/web${GREEN}...${ENDL}"
		cd web # Change context
		printf "${LIGHTGREEN}Downloading dependencies.${ENDL}"
		yarn # Download dependencies
		printf "${LIGHTGREEN}Done.${ENDL}"
		printf "${GREEN}Initializing ${BLUE}@lahsone${YELLOW}/app${GREEN}...${ENDL}" #TODO
		printf "${LIGHTGREEN}Done.${ENDL}"
		printf "${GREEN}Finished initializing!${ENDL}"
	;;
	"run")
		case "$2" in
			"web")
				printf "${GREEN}Starting ${BLUE}@lahsone${YELLOW}/web${GREEN}...${ENDL}"
				rsync -r --delete --exclude 'node_modules' --exclude yarn.lock --exclude package.json common/. web/src/common # Force sync initially
				cd web # Change context
				yarn start # Start with yarn
			;;
			"ios")
				echo "Running for ios!" #TODO
			;;
			"android")
				echo "Running for android" #TODO
			;;
			*)
				echo "Need to select a target: web | ios | android"
				exit 1
				;;
		esac
	;;
	"sync")
		rsync -r --delete --exclude 'node_modules' --exclude yarn.lock --exclude package.json common/. web/src/common
	;;
	"help")
		case "$2" in
			"")
			printf "${BLUE}@lahsone${YELLOW}/lahsone${GREEN} is a CLI(Command Line Interface) developed to automate some tasks in this project.${ENDL}"
			echo "Use \"./lahsone help [action]\" to get specific help about an action."
			echo "Here's the list of actions:"
			printf "\t- help\n\t- init\n\t- run\n\t- sync\n"
			;;
			"help") echo "List of actions."
			;;
			"init") echo "Initialize or update dependencies and the project files."
			;;
			"run") echo "Run the project in debug mode."
			;;
			"sync") echo "Synchronize the content in @lahsone/common to @lahsone/*"
			;;
			*) echo "Unrecognized command. Use \"./lahsone help\" without arguments for a list of actions."
			;;
		esac
	;;
	*)
		echo "Unrecognized command. Use \"./lahsone help\" for help"
	;;
esac

